application: ben-shope
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^fabfile\.py

handlers:
- url: /favicon\.ico
  static_files: app/img/favicon.ico
  upload: app/img/favicon\.ico
- url: /app
  static_dir: app
- url: /partials
  static_dir: app/partials
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest