application: ben-shope
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /static
  static_dir: static
- url: /json/.*
  script: main.app
- url: /user/.*
  script: main.app
- url: .*
  static_files: static/html/index.html
  upload: static/html/index.html

libraries:
- name: webapp2
  version: latest